version: '3.7'
services:
  web:
    image: untadee/survey-api:latest
    build: .
    ports:
      - "3333:3333"
    networks:
      - webnet
      - traefik-public
    depends_on:
      - redis
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.survey-web.rule=Host(`rais.dista.uninsubria.it`)
      - traefik.http.routers.traefik-public-https.entrypoints=https
      - traefik.http.routers.traefik-public-https.tls=true
      # - traefik.http.middlewares.survey-strip-prefix.stripprefix.prefixes=/survey
      # - traefik.http.routers.survey-web.middlewares=survey-strip-prefix
      - traefik.http.services.traefik-public.loadbalancer.server.port=3333
    # service deployment
    deploy:
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.50'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.50'
          memory: 256M
      # service restart policy
      # replicas: 4
      # update_config:
      #   parallelism: 2
      #   order: start-first
      #   failure_action: rollback
      #   delay: 10s
      # rollback_config:
      #   parallelism: 0
      #   order: stop-first
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
      #   window: 120s
  redis:
    image: redis:6.0-rc1
    ports:
      - "6378:6379"
    volumes:
      - data:/home/docker/data
    networks:
      - webnet
    deploy:
      # replicas: 4
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes

networks:
  webnet:
  traefik-public:
    external: true
volumes:
  data:


