version: '3.7'
services:
  web:
    image: untadee/survey-api:latest
    build: .
    ports:
      - "3333:3333"
    networks:
      - webnet
    depends_on:
      - redis
    # service deployment
    deploy:
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.50'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.50'
          memory: 256M
      # service restart policy
      # replicas: 4
      # update_config:
      #   parallelism: 2
      #   order: start-first
      #   failure_action: rollback
      #   delay: 10s
      # rollback_config:
      #   parallelism: 0
      #   order: stop-first
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
      #   window: 120s
  redis:
    image: redis:6.0-rc1
    ports:
      - "6378:6379"
    volumes:
      - data:/home/docker/data
    deploy:
      # replicas: 4
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet

networks:
  webnet:

volumes:
  data: