# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2
      
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 193.206.183.134
        username: son.ha
        password: son.ha1320
        port: 1904
        source: "docker-compose.yml,deploy.sh"
        target: "/home/son.ha/github-deployment/survey-2"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 193.206.183.134
        username: son.ha
        password: son.ha1320
        port: 1904
        script: cd /home/son.ha/github-deployment/survey-2 && sh deploy.sh
    
